development:
  adapter: postgresql
  database: ecommerce_site
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: 123456789
  port: 5432

test:
  adapter: postgresql
  database: ecommerce_site
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: 123456789
  port: 5432

production:
  adapter: postgresql
  database: ecommerce_site
  pool: 5
  timeout: 5000
  username: postgres
  host: localhost
  password: 123456789
  port: 5432
