# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8418d3ebd72136ed46e725c2f6793eca90ee3ec5afa893e413a77e010c5a25273fe397529a7a1d2dd411fe4180386227c9b53453197dcfd7f880f6d7fbc6f4d5

test:
  secret_key_base: bc58051407aa1780158fb8a2d72afa496c6998f93f53c022aefc072a462ec5a20eb050dd34f620019d190949b92d0f2944b926efbcedb35df0a0c8164e2942ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
